@echo off
echo Installing dependencies...
call npm install
echo Building web UI...
call npm run build
echo Configuring Claude Code hooks...
echo y | node bin/cli.js init
echo Starting Claudia...
node bin/cli.js
